sudo: false

language: go

go:
    - 1.6
    - tip

notifications:
    email: false

before_install:
    - export PATH=$PATH:$HOME/gopath/bin
    - go get golang.org/x/tools/cmd/cover
    - go get github.com/mattn/goveralls
    - go get github.com/GeertJohan/fgt
    - go get github.com/alecthomas/gometalinter
    - gometalinter --install

install:
    - go get .

script:
    - make testlint
    - make example
    - go test -v -tags testing -covermode=set -coverprofile=profile.cov ./...
    - goveralls -coverprofile=profile.cov -service=travis-ci -repotoken 5ZqQy0HNoFzGLyCfwptZj0Av4BUdOrZWA
